positions:
  - Data Engineer
locations:
  - United States
  - Canada
username: '<username>'
password: '<password>'
phone_number: '<>'
salary: '300000'
rate: '80'
output_filename: output.csv
blacklist: [ ]
blackListTitles: []
uploads:
  Resume: Resume.pdf
  #Cover Letter: /path/to/cover_letter.pdf
